# These are supported funding model platforms

github: [kurubaran19]
ko_fi: kurubaran19
liberapay: kurubaran19
issuehunt: kurubaran19
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
